### ISSUE TITLE
Nodelet error when running synced_rgbd.launch file

### ISSUE THREAD

**Issue by Murali25111993** [aliasghar53/autonomous-robot#1]
when running the roslaunch synced_rgbd.launch  we get following error.

Hardware:
Intel realsense D455
Nvidia NX
Ubuntu 20.04 Noetic

`[ERROR] [1694080672.404944416]: Failed to load nodelet [/rgbd_sync] of type [rtabmap_ros/rgbd_sync] even after refreshing the cache: According to the loaded plugin descriptions the class rtabmap_ros/rgbd_sync with base class type nodelet::Nodelet does not exist. Declared types are  RobotLocalization/EkfNodelet RobotLocalization/NavSatTransformNodelet RobotLocalization/UkfNodelet SlamGMappingNodelet apriltag_ros/ContinuousDetector depth_image_proc/convert_metric depth_image_proc/crop_foremost depth_image_proc/disparity depth_image_proc/point_cloud_xyz depth_image_proc/point_cloud_xyz_radial depth_image_proc/point_cloud_xyzi depth_image_proc/point_cloud_xyzi_radial depth_image_proc/point_cloud_xyzrgb depth_image_proc/point_cloud_xyzrgb_radial depth_image_proc/register image_proc/crop_decimate image_proc/crop_nonZero image_proc/crop_non_zero image_proc/debayer image_proc/rectify image_proc/resize image_publisher/image_publisher image_rotate/image_rotate image_view/disparity image_view/image imu_filter_madgwick/ImuFilterNodelet laser_filters/scan_to_cloud_filter_chain nodelet_tutorial_math/Plus pcl/BAGReader pcl/BoundaryEstimation pcl/ConvexHull2D pcl/CropBox pcl/EuclideanClusterExtraction pcl/ExtractIndices pcl/ExtractPolygonalPrismData pcl/FPFHEstimation pcl/FPFHEstimationOMP pcl/MomentInvariantsEstimation pcl/MovingLeastSquares pcl/NodeletDEMUX pcl/NodeletMUX pcl/NormalEstimation pcl/NormalEstimationOMP pcl/NormalEstimationTBB pcl/PCDReader pcl/PCDWriter pcl/PFHEstimation pcl/PassThrough pcl/PointCloudConcatenateDataSynchronizer pcl/PointCloudConcatenateFieldsSynchronizer pcl/PrincipalCurvaturesEstimation pcl/ProjectInliers pcl/RadiusOutlierRemoval pcl/SACSegmentation pcl/SACSegmentationFromNormals pcl/SHOTEstimation pcl/SHOTEstimationOMP pcl/SegmentDifferences pcl/StatisticalOutlierRemoval pcl/VFHEstimation pcl/VoxelGrid realsense2_camera/RealSenseNodeFactory rtabmap_legacy/data_odom_sync rtabmap_legacy/data_throttle rtabmap_legacy/obstacles_detection_old rtabmap_legacy/stereo_throttle rtabmap_legacy/undistort_depth rtabmap_odom/icp_odometry rtabmap_odom/rgbd_odometry rtabmap_odom/rgbdicp_odometry rtabmap_odom/stereo_odometry rtabmap_slam/rtabmap rtabmap_sync/rgb_sync rtabmap_sync/rgbd_sync rtabmap_sync/rgbdx_sync rtabmap_sync/rtabmap rtabmap_sync/stereo_sync rtabmap_util/disparity_to_depth rtabmap_util/imu_to_tf rtabmap_util/lidar_deskewing rtabmap_util/obstacles_detection rtabmap_util/point_cloud_aggregator rtabmap_util/point_cloud_assembler rtabmap_util/point_cloud_xyz rtabmap_util/point_cloud_xyzrgb rtabmap_util/pointcloud_to_depthimage rtabmap_util/rgb_sync rtabmap_util/rgbd_relay rtabmap_util/rgbd_split rtabmap_util/stereo_sync stereo_image_proc/disparity stereo_image_proc/point_cloud2
[ERROR] [1694080672.405222915]: The error before refreshing the cache was: According to the loaded plugin descriptions the class rtabmap_ros/rgbd_sync with base class type nodelet::Nodelet does not exist. Declared types are  RobotLocalization/EkfNodelet RobotLocalization/NavSatTransformNodelet RobotLocalization/UkfNodelet SlamGMappingNodelet apriltag_ros/ContinuousDetector depth_image_proc/convert_metric depth_image_proc/crop_foremost depth_image_proc/disparity depth_image_proc/point_cloud_xyz depth_image_proc/point_cloud_xyz_radial depth_image_proc/point_cloud_xyzi depth_image_proc/point_cloud_xyzi_radial depth_image_proc/point_cloud_xyzrgb depth_image_proc/point_cloud_xyzrgb_radial depth_image_proc/register image_proc/crop_decimate image_proc/crop_nonZero image_proc/crop_non_zero image_proc/debayer image_proc/rectify image_proc/resize image_publisher/image_publisher image_rotate/image_rotate image_view/disparity image_view/image imu_filter_madgwick/ImuFilterNodelet laser_filters/scan_to_cloud_filter_chain nodelet_tutorial_math/Plus pcl/BAGReader pcl/BoundaryEstimation pcl/ConvexHull2D pcl/CropBox pcl/EuclideanClusterExtraction pcl/ExtractIndices pcl/ExtractPolygonalPrismData pcl/FPFHEstimation pcl/FPFHEstimationOMP pcl/MomentInvariantsEstimation pcl/MovingLeastSquares pcl/NodeletDEMUX pcl/NodeletMUX pcl/NormalEstimation pcl/NormalEstimationOMP pcl/NormalEstimationTBB pcl/PCDReader pcl/PCDWriter pcl/PFHEstimation pcl/PassThrough pcl/PointCloudConcatenateDataSynchronizer pcl/PointCloudConcatenateFieldsSynchronizer pcl/PrincipalCurvaturesEstimation pcl/ProjectInliers pcl/RadiusOutlierRemoval pcl/SACSegmentation pcl/SACSegmentationFromNormals pcl/SHOTEstimation pcl/SHOTEstimationOMP pcl/SegmentDifferences pcl/StatisticalOutlierRemoval pcl/VFHEstimation pcl/VoxelGrid realsense2_camera/RealSenseNodeFactory rtabmap_legacy/data_odom_sync rtabmap_legacy/data_throttle rtabmap_legacy/obstacles_detection_old rtabmap_legacy/stereo_throttle rtabmap_legacy/undistort_depth rtabmap_odom/icp_odometry rtabmap_odom/rgbd_odometry rtabmap_odom/rgbdicp_odometry rtabmap_odom/stereo_odometry rtabmap_slam/rtabmap rtabmap_sync/rgb_sync rtabmap_sync/rgbd_sync rtabmap_sync/rgbdx_sync rtabmap_sync/rtabmap rtabmap_sync/stereo_sync rtabmap_util/disparity_to_depth rtabmap_util/imu_to_tf rtabmap_util/lidar_deskewing rtabmap_util/obstacles_detection rtabmap_util/point_cloud_aggregator rtabmap_util/point_cloud_assembler rtabmap_util/point_cloud_xyz rtabmap_util/point_cloud_xyzrgb rtabmap_util/pointcloud_to_depthimage rtabmap_util/rgb_sync rtabmap_util/rgbd_relay rtabmap_util/rgbd_split rtabmap_util/stereo_sync stereo_image_proc/disparity stereo_image_proc/point_cloud2
[FATAL] [1694080672.406587123]: Failed to load nodelet '/rgbd_sync` of type `rtabmap_ros/rgbd_sync` to manager `nodelet_manager'`

Please guide.

**Comment by aliasghar53** [comment]
Have you installed [rtabmap_ros](https://github.com/introlab/rtabmap_ros)?

**Comment by Murali25111993** [comment]
Yes, I have installed on both remote computer and also in robot(NVIDIA) both has ROS Noetic, Ubuntu 20.04. 
rs_rgbd.launch working perfectly fine. 
Earlier i used to create map using realsense2_camera opensource_tracking.launch which uses rs_camera.launch and rtabmap.launch. 

I think only nodelet package is causing problem. Any dependencies i have to install?

Whether I need to create any nodelet c++ program.?

**Comment by Murali25111993** [comment]
The error is not visible in ros-melodic, but visible in ros-noetic. Checking for the cause

**Comment by Murali25111993** [comment]
According to the issue in rtabmap [link](https://github.com/introlab/rtabmap_ros/issues/949),I modified the launch file accordingly.

In synced_rgbd.launch,

Modified the launch file as
`    <node pkg="nodelet" type="nodelet" name="rtabmap_sync/rgbd_sync" args="load rtabmap_sync/rgbd_sync nodelet_manager" output="screen">`

Thereby resolved the issue. Thanks
